"""Add university to user

Revision ID: 876e4ba08d46
Revises: 38118ee54e9d
Create Date: 2026-01-04 13:29:10.252009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876e4ba08d46'
down_revision: Union[str, Sequence[str], None] = '38118ee54e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('university', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'university')
    # ### end Alembic commands ###
